transform state
mate-academy/js_stateful-clones pull request #1137
Opened 2022-04-30 13:54 UTC by ISRLv2021

2022-05-02 12:47 UTC, valerii-derkach requested changes

2022-05-02 12:47 UTC, valerii-derkach commented on src/transformStateWithClones.js
> +    if (actions[i].type === 'addProperties') {
use switch (actions[i].type) 
case 'addProperties' ... instead of if/else 
because you repeat the same code 3 times

2022-05-02 18:33 UTC, Anna-Tkachenko requested changes

2022-05-02 18:33 UTC, Anna-Tkachenko commented on src/transformStateWithClones.js
> +        }
Where is break?

2022-05-02 18:33 UTC, Anna-Tkachenko commented on src/transformStateWithClones.js
> +    }
Don't forget about default case for switch / case statement

2022-05-03 11:24 UTC, Anna-Tkachenko requested changes
You didn't fix my comments

2022-05-03 19:11 UTC, Anna-Tkachenko approved these changes

2022-12-21 21:01 UTC, closed without merging