my solution with case
mate-academy/js_stateful-clones pull request #1178
Opened 2022-06-06 13:49 UTC by Pavlo000

2022-06-07 13:19 UTC, mira1zu requested changes
👍
Привет! Всё отлично за исключением пары моментов

2022-06-07 13:19 UTC, mira1zu commented on src/transformStateWithClones.js
> +        for (const j of keysToRemove) {
Что такое j, почему именно j? Вероятно, тут можно использовать что-то более подходящее, типа key?

2022-06-07 13:19 UTC, mira1zu commented on src/transformStateWithClones.js
> +        }
Очистку всего обьекта можно сделать проще и без цикла)

2022-06-07 15:23 UTC, Pavlo000 commented
Спасибо за ревю, исправил ошибки

вт, 7 июн. 2022 г. в 16:19, Bogdan Poshtarenko ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> 👍
> Привет! Всё отлично за исключением пары моментов
> ------------------------------
>
> In src/transformStateWithClones.js
> <https://github.com/mate-academy/js_stateful-clones/pull/1178#discussion_r891212329>
> :
>
> > @@ -7,7 +7,34 @@
>
>   * @return {Object[]}
>
>   */
>
>  function transformStateWithClones(state, actions) {
>
> -  // write code here
>
> +  const myActions = [];
>
> +  const cloneState = { ...state };
>
> +
>
> +  for (const action of actions) {
>
> +    const { type, extraData, keysToRemove } = action;
>
> +
>
> +    switch (type) {
>
> +      case 'addProperties':
>
> +        Object.assign(cloneState, extraData);
>
> +        break;
>
> +
>
> +      case 'removeProperties':
>
> +        for (const j of keysToRemove) {
>
>
> Что такое j, почему именно j? Вероятно, тут можно использовать что-то
> более подходящее, типа key?
> ------------------------------
>
> In src/transformStateWithClones.js
> <https://github.com/mate-academy/js_stateful-clones/pull/1178#discussion_r891213784>
> :
>
> > +        for (const key in cloneState) {
>
> +          delete cloneState[key];
>
> +        }
>
>
> Очистку всего обьекта можно сделать проще и без цикла)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/js_stateful-clones/pull/1178#pullrequestreview-998132823>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AY5PB6FSCFYEEB6IYD464MLVN5D6FANCNFSM5X7N3Y2A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-07 16:29 UTC, mira1zu approved these changes

2022-06-08 08:33 UTC, jstmpelowycz approved these changes

2022-06-08 08:33 UTC, jstmpelowycz commented on src/transformStateWithClones.js
> +  const myActions = [];
I'd rather say `arrayOfActions`

2024-11-26 18:13 UTC, closed without merging