Solution
mate-academy/js_stateful-clones pull request #1689
Opened 2022-11-14 17:39 UTC by panianchuk

2022-11-15 15:53 UTC, Bohdan-Maksymiuk requested changes

2022-11-15 15:53 UTC, Bohdan-Maksymiuk commented on src/transformStateWithClones.js
> +  for (const action of actions) {
also use [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) for usage of type, extraData, keysToRemove

2022-11-15 15:53 UTC, Bohdan-Maksymiuk commented on src/transformStateWithClones.js
> +    }
avoid such nesting `else if` conditions
This code is hard to read and maintain

2022-11-16 07:47 UTC, Bohdan-Maksymiuk requested changes

2022-11-16 07:47 UTC, Bohdan-Maksymiuk commented on src/transformStateWithClones.js
> +        Object.assign(copyState, extraData);
```suggestion
    switch (type) {
      case 'addProperties':
        Object.assign(copyState, extraData);
```
Inappropriate usage of switch

2022-11-16 07:47 UTC, Bohdan-Maksymiuk commented on src/transformStateWithClones.js
> +        Object.assign(copyState, extraData);
[UL](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch)

2022-11-17 17:00 UTC, Viktor-Kost requested changes

2022-11-17 17:16 UTC, Viktor-Kost requested changes

2022-11-17 17:21 UTC, Viktor-Kost approved these changes

2023-12-29 10:54 UTC, closed without merging