solution
mate-academy/js_stateful-clones pull request #1762
Opened 2022-11-27 16:09 UTC by olena-yanovska

2022-11-28 09:53 UTC, viktoriia-kravchenko approved these changes
🔥

2022-11-28 13:56 UTC, Ihor-Karpyn requested changes

2022-11-28 13:56 UTC, Ihor-Karpyn commented on src/transformStateWithClones.js
> +  const clones = [];
Давай краще подумаємо над назвами змінних,можливо stateVersions

2022-11-28 13:56 UTC, Ihor-Karpyn commented on src/transformStateWithClones.js
> +  Object.assign(stateClone, state);
щось дивне, давай спробуємо позбутись цього

2022-11-30 09:32 UTC, Ihor-Karpyn approved these changes

2022-11-30 09:32 UTC, Ihor-Karpyn commented on src/transformStateWithClones.js
> +  const state = Object.assign({}, originState);
Частіше для копіювання використовується спред оператор

2023-11-10 20:53 UTC, closed without merging