task was solved
mate-academy/js_stateful-clones pull request #1933
Opened 2023-01-26 20:56 UTC by vanyachyzh

2023-01-27 17:35 UTC, IvanFesenko requested changes
Good job. Please fix code duplicating

2023-01-27 17:35 UTC, IvanFesenko commented on src/transformStateWithClones.js
> +      });
Do not repeat your self, do this action once at the end

2023-01-28 08:27 UTC, AlisaVlasova requested changes

2023-01-28 08:27 UTC, AlisaVlasova commented on src/transformStateWithClones.js
> +    if (actions[i].type === 'addProperties') {
use switch/case

2023-01-28 08:27 UTC, AlisaVlasova commented on src/transformStateWithClones.js
> +      for (const item in actions[i].extraData) {
you can use Object.assign instead for loop

2023-01-30 09:11 UTC, OlEzhA0 requested changes

2023-01-30 09:11 UTC, OlEzhA0 commented on src/transformStateWithClones.js
> +        break;
```suggestion
    switch (actions[i].type) {
      case 'addProperties':
        Object.assign(copy, actions[i].extraData);
        break;

      case 'removeProperties':
        for (let j = 0; j < actions[i].keysToRemove.length; j++) {
          delete copy[actions[i].keysToRemove[j]];
        };

        break;
```

2023-01-30 09:11 UTC, OlEzhA0 commented on src/transformStateWithClones.js
> +    });
?
```suggestion
    resultArray.push(copy);
```

2023-01-30 19:12 UTC, Viktor-Kost approved these changes

2024-03-07 18:43 UTC, closed without merging