state add
mate-academy/js_stateful-clones pull request #1983
Opened 2023-02-11 12:41 UTC by VadimDrobyazko

2023-02-11 15:21 UTC, VitaliyBondarenko1982 requested changes

2023-02-11 15:21 UTC, VitaliyBondarenko1982 commented on src/transformStateWithClones.js
> +  const massive = [];
better naming result or stateHistory...

2023-02-11 15:21 UTC, VitaliyBondarenko1982 commented on src/transformStateWithClones.js
> +        massive.push({ ...stateCopy });
repeating code. you can push in the end of iteration after switch

2023-02-11 15:21 UTC, VitaliyBondarenko1982 commented on src/transformStateWithClones.js
> +        }
```suggestion
        stateCopy = {}
```

2023-02-13 08:40 UTC, vlad-demchuk approved these changes

2024-06-09 08:38 UTC, closed without merging