solution
mate-academy/js_stateful-clones pull request #2322
Opened 2023-05-11 20:32 UTC by vitvadym

Had same troubles with pushing 😃

2023-05-12 08:05 UTC, dinaminahi requested changes
Well done 👍 
But few more things to improve it

2023-05-12 08:05 UTC, dinaminahi commented on src/transformStateWithClones.js
> +    const { type, keysToRemove, extraData } = action;
👍

2023-05-12 08:05 UTC, dinaminahi commented on src/transformStateWithClones.js
> +  let newState = { ...state };
Let't make it const and then you should change the way you are clearing it

2023-05-12 08:05 UTC, dinaminahi commented on src/transformStateWithClones.js
> +        }
Consider of creating separate function for this to make `switch-case` smaller and more readable

2023-05-15 07:56 UTC, naziamoff approved these changes
🔥

2024-11-22 21:05 UTC, closed without merging