Solution
mate-academy/js_stateful-clones pull request #283
Opened 2020-09-24 16:48 UTC by xipholena

2020-09-24 17:42 UTC, EVolokhin reviewed
прикольно со свитч кейсом вышло.... я поленился переделывать :)

2020-09-24 17:42 UTC, EVolokhin commented on src/transformStateWithClones.js
> +  for (const { operation: task, properties: keys } of transforms) {
можно было не задавать имена переменным просто оставить { operation, properties }  и потом так к ним и обращаться

2020-09-24 17:42 UTC, EVolokhin commented on src/transformStateWithClones.js
> +        for (const toRemove of keys) {
вот если бы не задавала название переменных деструктурированному объекту в строке 72 то не пришлось бы выдумывать новые имена :)  оставила бы стандартное название key  и получилось бы  (const key of properties)
ключ  пропертис который нужно удалить из клона

2020-09-24 17:52 UTC, xipholena commented on src/transformStateWithClones.js
> +  for (const { operation: task, properties: keys } of transforms) {
Най буде) для різноманіття) Взагалі, мені здалося спочатку, що якщо залишити то легше заплутатись... але зараз роблю деструктуризацію на Stateful object і, в принципі, вже не плутаюсь)

2020-09-24 17:54 UTC, xipholena commented on src/transformStateWithClones.js
> +        for (const toRemove of keys) {
Я ледаще з попереднього ці змінні взяла

2020-09-24 17:57 UTC, EVolokhin commented on src/transformStateWithClones.js
> +        for (const toRemove of keys) {
ну код переписать на свич кейс не поленилась же .....

2020-09-25 07:06 UTC, solaryasha requested changes

2020-09-25 07:06 UTC, solaryasha commented on src/transformStateWithClones.js
> +  const clone = { ...state };
```suggestion
  const stateClone = { ...state };
```

2020-09-25 07:06 UTC, solaryasha commented on src/transformStateWithClones.js
> +        for (const toRemove of keys) {
Дієсловами називаємо функції,  тому краще давай підберемо кращу назву.

2020-09-25 07:06 UTC, solaryasha commented on src/transformStateWithClones.js
> +  const newArray = [];
```suggestion
  const states = [];
```

2020-09-25 07:06 UTC, solaryasha commented on src/transformStateWithClones.js
> +        for (const toClearAll in clone) {
Тут так само.

2020-09-25 07:19 UTC, xipholena commented on src/transformStateWithClones.js
> +        for (const toRemove of keys) {
так я пригадала просто. І дарма, як виявилось)

2020-09-28 06:59 UTC, Vladimir-Beliy approved these changes

2020-09-28 06:59 UTC, Vladimir-Beliy commented on src/transformStateWithClones.js
> +  for (const { operation: task, properties: keys } of transforms) {
нет смысла называть эти переменные иначе

2020-12-10 16:53 UTC, closed without merging