done task
mate-academy/js_stateful-clones pull request #3175
Opened 2024-01-30 20:13 UTC by denisbielykh

2 solutions

-на 80 рядку зробив перенос бо лінтер сварився, що більше 80 символів у рядку

2024-01-30 20:23 UTC, Viktor-Kost requested changes

2024-01-30 20:23 UTC, Viktor-Kost commented on src/transformStateWithClones.js
> +//     }
remove all commented code

2024-01-30 20:23 UTC, Viktor-Kost commented on src/transformStateWithClones.js
> +  const stateVersions = [];
this is redundant
```suggestion
```

2024-01-30 20:23 UTC, Viktor-Kost commented on src/transformStateWithClones.js
> +  stateVersions[0] = { ...state };
```suggestion
  let currentState = { ...state };
```

2024-01-30 20:23 UTC, Viktor-Kost commented on src/transformStateWithClones.js
> +    let changedState;
redundant
```suggestion
```

2024-01-30 20:23 UTC, Viktor-Kost commented on src/transformStateWithClones.js
> +        changedState = addProperties(lastStateVersion, action.extraData);
```suggestion
        addProperties(currentState, action.extraData);
```

2024-01-30 20:23 UTC, Viktor-Kost commented on src/transformStateWithClones.js
> +        );
```suggestion
        removeProperties(currentState, action.keysToRemove);
```

2024-01-30 20:23 UTC, Viktor-Kost commented on src/transformStateWithClones.js
> +    stateVersions.push(changedState);
```suggestion
    finalStateHistory.push({ ...currentState });
```

2024-02-01 18:30 UTC, maxim2310 approved these changes
Well done!!!

2024-06-14 10:32 UTC, closed without merging