Stateful-clones
mate-academy/js_stateful-clones pull request #3511
Opened 2024-05-09 18:31 UTC by Svitlana-Vitryk

2024-05-09 18:40 UTC, maxim2310 requested changes
Good work, but lets make some improvement

2024-05-09 18:40 UTC, maxim2310 commented on src/transformStateWithClones.js
> +      );
more easier way) 
```suggestion
        for (const key of action.keysToRemove) {
          delete currentState[key];
        }
```

2024-05-09 18:40 UTC, maxim2310 commented on src/transformStateWithClones.js
> +    if (action.type === 'clear') {
better use "switch case" in this case

2024-05-13 11:33 UTC, lerastarynets approved these changes
Keep up the great work!

2025-01-15 17:22 UTC, closed without merging