solution
mate-academy/js_stateful-clones pull request #374
Opened 2020-12-27 11:23 UTC by eugenekh81

2020-12-28 10:07 UTC, vpolets requested changes

2020-12-28 10:07 UTC, vpolets commented on src/transformStateWithClones.js
> +      result.push(Object.assign({}, stateClone));
повторююється в кожному if, можна виносити за межі і писати тільки раз

2020-12-28 10:07 UTC, vpolets commented on src/transformStateWithClones.js
> +  }
```suggestion
    }
    
    result.push({ ...stateClone })
  }
```

2020-12-28 10:07 UTC, vpolets commented on src/transformStateWithClones.js
> +    }
тут якраз була хороша можливість використати switch case

2020-12-28 10:07 UTC, vpolets commented on src/transformStateWithClones.js
> +  let stateClone = Object.assign({}, state);
в тебе немає потреби заміняти посилання на клон тому const
```suggestion
  const stateClone = Object.assign({}, state);
```

2020-12-28 10:07 UTC, vpolets commented on src/transformStateWithClones.js
> +  for (let i = 0; i < transforms.length; i++) {
тут ідеально підійде for ... of 
не бійся їх використовувати
індекси ускладнюють читабельність

2020-12-28 10:07 UTC, vpolets commented on src/transformStateWithClones.js
> +  for (let i = 0; i < transforms.length; i++) {
```suggestion
  for (const { operation, properties } of transforms) {
```

2020-12-28 10:07 UTC, vpolets commented on src/transformStateWithClones.js
> +      stateClone = {};
видали всі ключики як в попередньому завданні, це буде краще (знаю що в умові про це сказано)

2020-12-29 12:16 UTC, eugenekh81 commented
К сожалению, пока мне не удалось решить, как создавать новый чистый stateClone не присваивая ему новое значение в операции clear :( буду  благодарен за подсказку :)

2020-12-29 17:16 UTC, vkryvytskyy approved these changes

2020-12-29 17:16 UTC, vkryvytskyy commented on src/transformStateWithClones.js
> +        stateClone = {};
> К сожалению, пока мне не удалось решить, как создавать новый чистый stateClone не присваивая ему новое значение в операции clear :( буду благодарен за подсказку :)

```
for (const key in stateClone) {
  delete
```

так же как ты в предыдущем задании делал

2020-12-30 13:28 UTC, eugenekh81 commented
Получилось, спасибо больше за комментарии!

2021-01-04 09:19 UTC, vpolets approved these changes

2021-01-04 09:19 UTC, vpolets commented on src/transformStateWithClones.js
> +        result.push(Object.assign({}, stateClone));
result.push зустрічається в кожному case
Його можна винести за switch case

2024-01-16 14:48 UTC, closed without merging