State clones
mate-academy/js_stateful-clones pull request #461
Opened 2021-03-29 20:33 UTC by ivan-major

2021-03-30 10:19 UTC, vpolets requested changes

2021-03-30 10:19 UTC, vpolets commented on src/transformStateWithClones.js
> +  for (let i = 0; i < transforms.length; i++) {
використай for of

2021-03-30 10:19 UTC, vpolets commented on src/transformStateWithClones.js
> +    }
switch case більше сюди підійде

2021-03-30 10:19 UTC, vpolets commented on src/transformStateWithClones.js
> +      stateClones.push({ ...newState });
повторюється в кожному case варто винести за switch

2021-03-30 10:19 UTC, vpolets commented on src/transformStateWithClones.js
> +      for (let k = 0; k < transforms[i].properties.length; k++) {
for of

2021-03-30 13:26 UTC, ivan-major commented on src/transformStateWithClones.js
> +      for (let k = 0; k < transforms[i].properties.length; k++) {
Добрий день.

Зробив необхідні зміни.

Дякую.

2021-04-02 14:17 UTC, vkryvytskyy requested changes

2021-04-02 14:17 UTC, vkryvytskyy commented on src/transformStateWithClones.js
> +  for (const i of transforms) {
what does `i` means?

2021-04-02 14:17 UTC, vkryvytskyy commented on src/transformStateWithClones.js
> +          }
this if is redundant

2021-04-02 14:17 UTC, vkryvytskyy commented on src/transformStateWithClones.js
> +        for (const k in i.properties) {
what does `k` means?

2021-04-05 11:05 UTC, vkryvytskyy approved these changes

2025-01-26 12:41 UTC, closed without merging