solution
mate-academy/js_stateful-clones pull request #471
Opened 2021-04-21 16:14 UTC by Ihor-Karpyn

2021-04-21 17:33 UTC, igor-stasiv approved these changes

2021-04-22 07:23 UTC, aliceblunt8 requested changes

2021-04-22 07:23 UTC, aliceblunt8 commented on src/transformStateWithClones.js
> +  }
you can push changed state at the end of each loop

```suggestion
  for (const transform of transforms) {
    switch (transform.operation) {
      case 'clear':
        initialState = {};
        break;

      case 'addProperties':
        Object.assign(initialState, transform.properties);
        break;
        
      case 'removeProperties':
        for (const key of transform.properties) {
          delete initialState[key];
        }
        break;
    }
    
     changesList.push({ ...initialState });
  }
```

2021-04-22 09:08 UTC, aliceblunt8 approved these changes

2024-11-22 17:44 UTC, closed without merging