solution
mate-academy/js_stateful-clones pull request #510
Opened 2021-04-25 13:52 UTC by BilliZane

2021-04-26 07:36 UTC, stas-dukach approved these changes
good

2021-04-26 08:19 UTC, varseniuk approved these changes
Good! 👍 
But don't forget to add `default` case to your `switch` statement

2021-04-26 08:19 UTC, varseniuk commented on src/transformStateWithClones.js
> +  };
```suggestion
  let stateClone = { ...state };
```
You can write it in one line but it's ok

2021-04-26 08:19 UTC, varseniuk commented on src/transformStateWithClones.js
> +  function add(properties) {
```suggestion
  function add(properties) {
```
👍

2021-04-26 08:19 UTC, varseniuk commented on src/transformStateWithClones.js
> +    };
add `default` case

2021-04-28 10:36 UTC, mykola-yarchuk requested changes
test

2021-04-28 10:36 UTC, mykola-yarchuk approved these changes

2023-09-26 15:08 UTC, closed without merging