Solution?
mate-academy/js_stateful-clones pull request #581
Opened 2021-06-24 09:53 UTC by Vivdyuk

2021-06-24 10:21 UTC, sergei-trofimov approved these changes
🚀

2021-06-24 11:08 UTC, ArtemTopolskyi requested changes

2021-06-24 11:08 UTC, ArtemTopolskyi commented on src/transformStateWithClones.js
> +        transformClones.push({ ...newState });
трижды дублируешь один и тот же код, можно просто вынести в конец цикла

2021-06-25 08:43 UTC, ArtemTopolskyi approved these changes

2021-06-25 08:43 UTC, ArtemTopolskyi commented on src/transformStateWithClones.js
> +  const newState = {
```suggestion
  const stateClone = {
```
do not use words like 'new' in variable names

2023-03-01 10:28 UTC, closed without merging