Solution
mate-academy/js_stateful-clones pull request #985
Opened 2022-02-09 15:42 UTC by VladBrynzia

2022-02-09 17:28 UTC, Olexandr-Trubin-Koshyk approved these changes
Good job! 💪

2022-02-10 10:11 UTC, Ihor-Karpyn requested changes
`arr.push({ ...state2 });` don't repeat yourself

2022-02-10 10:11 UTC, Ihor-Karpyn commented on src/transformStateWithClones.js
> +        }
```suggestion
        state2 = {};
```

2022-02-10 10:11 UTC, Ihor-Karpyn commented on src/transformStateWithClones.js
> +  const state2 = { ...state };
not clear

2022-02-15 10:22 UTC, solaryasha requested changes

2022-02-15 10:22 UTC, solaryasha commented on src/transformStateWithClones.js
> +  const array = [];
Уникай назви структур данних,

2022-02-15 10:22 UTC, solaryasha commented on src/transformStateWithClones.js
> +  }
Це зайве

2022-02-15 10:22 UTC, solaryasha commented on src/transformStateWithClones.js
> +        arrayPush();
Дублюєш код в двох місцях, напиши його після switch один раз

2022-02-17 12:09 UTC, solaryasha requested changes

2022-02-17 12:09 UTC, solaryasha commented on src/transformStateWithClones.js
> +  const resultArr = [];
https://mateacademy.slack.com/archives/C02T596SHUZ/p1644845021054899

2022-02-17 12:09 UTC, solaryasha commented on src/transformStateWithClones.js
> +  for (const keys of actions) {
```suggestion
  for (const action of actions) {
```

2022-02-21 12:23 UTC, Ihor-Karpyn approved these changes

2022-12-14 15:37 UTC, closed without merging